### ISSUE TITLE
Tray icon problems

### ISSUE THREAD

**Issue by kukkjanos** [philipl/pidgin-indicator#15]
Hi Philip,

I have two problems.
First:
If lock and unlock screensaver then the indicator tray icon is dies. (Ubuntu 14.04, Gnome Shell)

Second:
Unfortunately still not blink tray icon (Ubuntu 14.04, Gnome Shell)

Solvable the problems a new upgrade? Do you think?

**Comment by philipl** [comment]
If you're using Gnome Shell, then you're not using Unity, which is what renders indicators on a default Ubuntu desktop. Presumably you are using https://github.com/rgcjonas/gnome-shell-extension-appindicator, which is where you should direct your questions. The indicator works correctly in Unity.
