### ISSUE TITLE
It should blink on a new message

### ISSUE THREAD

**Issue by johannesjo** [philipl/pidgin-indicator#16]
Or at least show a different icon. I activated "Blink on new message" but that does not seem to work. Testing on Ubuntu 14.04.

**Comment by philipl** [comment]
Using gnome shell? See issue 15.

**Comment by johannesjo** [comment]
No unity.

**Comment by philipl** [comment]
How did you install it?

**Comment by johannesjo** [comment]
Like described here: http://www.webupd8.org/2014/01/pidgin-indicator-ubuntu-appindicator.html

```
sudo add-apt-repository ppa:nilarimogard/webupd8
sudo apt-get update
sudo apt-get install pidgin-indicator
```

**Comment by philipl** [comment]
I have 0.9-1~webupd8~utopic0 installed here on my 14.10 system and it works great. I have not tested with 14.04 - maybe the indicator support there doesn't work with the mechanism I used to switch the icon (and I'm not aware of any other way to switch the icon)

**Comment by johannesjo** [comment]
Thats unfortunate :)
