### ISSUE TITLE
Left click behaviour on Kubuntu

### ISSUE THREAD

**Issue by hrk** [philipl/pidgin-indicator#17]
From the description of the project:
```
* The 'smart' click behaviour that either shows the buddy list or unread
  messages is now activated by a middle-click - because left click on an
  indicator always opens the menu.
```
This, however, is not the expected behaviour with KDE Plasma5, where an indicator is activated via the left click, and the menu is shown on a right click.

Could you please add an automated way to react on clicks depending on the environment (Ubuntu vs KDE/Kubuntu) if possible, or at the very least an option to select the behaviour?

**Comment by philipl** [comment]
As you might be aware of, click policy is controlled by the indicator renderer and not the indicator itself. What I've described is what happens in Unity. I have no idea what policy the KDE renderer implements, but if you're unsatisfied with it , you need to discuss that with the maintainers.

**Comment by hrk** [comment]
I was not aware of that, thank you for the clarigication.
