### ISSUE TITLE
Fedora Package for Plasma 5

### ISSUE THREAD

**Issue by radekvokal** [philipl/pidgin-indicator#19]
Hi, your plugin saved my life on Plasma 5 - Fedora 22. Here's an RPM-ified version 

http://copr.fedoraproject.org/coprs/rvokal/pidgin-indicator/

**Comment by philipl** [comment]
Thanks for the heads up. I'll add this to the documentation!

**Comment by rocketraman** [comment]
FYI: this is now available in the core Fedora repos: http://koji.fedoraproject.org/koji/packageinfo?packageID=22135
