### ISSUE TITLE
Left Click

### ISSUE THREAD

**Issue by JStyle21** [philipl/pidgin-indicator#20]
Hi Philip,

I have a question regarding the indicator, although obvious since i've seen mentions of this i wanted to know if it's possible to enable left click functionality (i haven't yet tested middle click).
Right click seems to work fine and left is disabled so i guess somehow they are separated even tho i read they should do the same thing.

**Comment by philipl** [comment]
Not sure what you mean. Click functionality is controlled by the 'container' application that actually renders the indicator. This means it can decide what the clicks do. In Unity, left click and right click do exactly the same things, and the special action is mapped to middle click. But KDE or GNOME or whatever might do things differently.

**Comment by JStyle21** [comment]
Thanks for the explanation. :)
