### ISSUE TITLE
Plasma 5: Left click no action

### ISSUE THREAD

**Issue by v00d00** [philipl/pidgin-indicator#21]
Under Plasma when you left click nothing seems to happen, middle works as expected and right brings up the menu. Is there anyway to have different mappings for KDE so that you can raise with left click (as other apps e.g. Quassel) do?

It sounds like different behaviour from Unity, so not sure if there is a way to detect?

Thanks!

**Comment by philipl** [comment]
See issue 20. What clicks do is a decision made by the indicator container (whichever part of Plasma that might be). This is deliberately abstracted from the indicators themselves.
