### ISSUE TITLE
100% cpu on KDE during blinking

### ISSUE THREAD

**Issue by neufeind** [philipl/pidgin-indicator#25]
During a new-message notification (blinking indicator) I see reproducible 100% cpu-usage on KDE (process: plasmashell). Of course I can't really tell if it might be the fault of KDE/plasma. But do you maybe have an idea to track this down?

**Comment by philipl** [comment]
Well, I guess it goes away if you turn off 'Blink on New Message'? Then it's a problem in plasmashell when dealing with the icon changing frequently. The only way to implement blinking is to change the icon continuously, so you should file a bug report with plasmashell.

**Comment by neufeind** [comment]
Thanks, plasmashell as the one to blame was also my guess. Issue opened there already.
Is there a way to just turn of the blinking (for the moment) but keep the new-message-icon instead? I searched for it in the plugin-settings - but there seem to be no settings for this plugin.

**Comment by philipl** [comment]
It's in the indicator menu itself - right above Quit.
