### ISSUE TITLE
On KDE, left-click to open buddy list rather than middle

### ISSUE THREAD

**Issue by rocketraman** [philipl/pidgin-indicator#26]
Thanks for this plugin! It fixes various issues with using the default indicator on KDE 5.

I see that this plugin uses middle-click to open the buddy list, I guess because left and right-click do the same thing on Ubunty Unity. However, on KDE, when I left-click the icon, nothing happens (not even the right-click menu comes up).

Can the plugin open the buddy indicator with left click on KDE? Because not even the right-click menu comes up in KDE when I left-click, this makes me think the fix might be just a matter of listening for another event type?

**Comment by philipl** [comment]
No, indicators do not get raw click events. This is a deliberate part of the design.

The indicator manager (Unity, Plasma, whatever it may be) decides what happens on left/middle/right.

In Unity, left and right are configured to show the menu while middle triggers the "secondary action". Nothing else is available, so I had no choice but to use the secondary action to show the list.

It sounds like KDE is configured to show the menu on right click, do the secondary action on middle click and do nothing on left click. You'll have to discuss this behaviour with the maintainers of whatever part of the system handles the indicators.

**Comment by rocketraman** [comment]
Thanks for your reply.

> You'll have to discuss this behaviour with the maintainers of whatever part of the system handles the indicators.

Just so I understand exactly what I'm discussing...

> It sounds like KDE is configured to show the menu on right click, do the secondary action on middle click and do nothing on left click.

When I left-click on other indicator icons (native ones like clipboard, bluetooth, audio, etc.) I do get some information related to that indicator. So I can't say KDE is configured to do nothing because clearly it isn't.  Is there some more detailed information I can provide to upstream?

**Comment by rocketraman** [comment]
> When I left-click on other indicator icons (native ones like clipboard, bluetooth, audio, etc.) I do get some information related to that indicator. So I can't say KDE is configured to do nothing because clearly it isn't. Is there some more detailed information I can provide to upstream?

Never mind, I think I understand the issue. For reference, I created this Fedora issue: https://bugzilla.redhat.com/show_bug.cgi?id=1319869

**Comment by philipl** [comment]
There are native icons and there are indicator based icons. I assume that the ones you listed are not indicator based, so their behaviour can be different.
