### ISSUE TITLE
Only "Pidgeon Head" icon is shown

### ISSUE THREAD

**Issue by sleeksorrow** [philipl/pidgin-indicator#29]
Since some days this plugin only shows the "purple pidgeon head" icon in the tray. It blinks when new messages appear, but that's about it.

Maybe the issue started with me updating KDE to Plasma 5.6.4 recently when it was pushed to Ubuntu Xenial kubuntu-backports PPA. I cannot tell for sure, but this is the only big change I did on my desktop environment.

I recompiled pidgin-indicator using recent git version, but no change.

Sadly I don't know where to start debugging, I will happily take suggestions on what to do to get more debug output.

**Comment by philipl** [comment]
This will be something inside KDE. There is nothing in the code which will set the pidgeon head as the icon under any conditions, so if it's happening, something in KDE is getting the icon from the application, some how.

**Comment by sleeksorrow** [comment]
Well I have to respect your decision as you are the one with the insight. Just to let you know, with the latest KDE update to Plasma 5.6.5 there even is no blinking anymore, so the indicator is completely useless. The more distributions update their Plasma packages, the uglier this issue will get.

**Comment by sleeksorrow** [comment]
After rebuilding the latest git clone, blinking works again, so please disregard my previous comment, it's still only the wrong icon showing (always the pidgeon head in any case)
