### ISSUE TITLE
Compatibility with python3

### ISSUE THREAD

**Issue by hoehnp** [philipl/pidgin-indicator#32]
As python2.7 is not EOL and pidgin-indicator seems to be in gentoo dependent on libapp-indicator in version 2, it does not compile anymore. I changed in my fork of this repo without success the version of appindicator to appindicator3-0.1. Do you have any advise to make the changes successful?

**Comment by philipl** [comment]
I tried changing it to appindicator3-0.1 and it worked fine for me. I'm actually surprised, as the difference between 3 and non-3 is that 3 is built with gtk3 and non-3 is built with gtk2, but pidgin is gtk2, so my rebuilt plugin will have pulled both versions of gtk into the running program, which seems really scary.

Anyway, the point here is that pidgin itself is what controls the gtk version in use, so we can't do anything about it.

**Comment by hoehnp** [comment]
@philipl: Thank you for your answer. I mistakenly read the 3 python as gentoo slowly migrates away from python 2.7. I will try now again by taking the correct dependencies to gtk3
